/**
 * SessionStart hook: mirror skills/ into the paths agents load from, then print an orientation.
 *
 * skills/ is the single tracked copy. Claude Code loads project skills from .claude/skills/, and
 * vendor-neutral tools read .agents/skills/, so both are generated here rather than committed three
 * times and allowed to drift. Each mirror carries a marker file; a mirror without one was created by
 * hand and is left alone instead of deleted.
 *
 * Two kinds of skill go into the mirrors, flattened side by side because agents load skills from one
 * flat directory:
 *
 *   skills/<name>/          written here, stating a rule this codebase already follows
 *   skills/vendor/<name>/   copied verbatim from another repo at a pinned commit (skills/vendor/vendored.json)
 *
 * A first-party skill wins a name collision, since it is the one that describes this repo.
 *
 * Never blocks a session: any failure is reported and the hook exits 0.
 */
import { cpSync, existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = dirname(dirname(dirname(fileURLToPath(import.meta.url)))) // .claude/hooks -> repo root
const SOURCE = join(ROOT, 'skills')
const VENDOR = join(SOURCE, 'vendor')
const MARKER = '.generated-by-sync-skills'
const MIRRORS = [join(ROOT, '.claude', 'skills'), join(ROOT, '.agents', 'skills')]

function skillsIn(base) {
  if (!existsSync(base)) return []
  return readdirSync(base, { withFileTypes: true })
    .filter((e) => e.isDirectory() && existsSync(join(base, e.name, 'SKILL.md')))
    .map((e) => e.name)
    .sort()
}

function mirror(groups) {
  for (const dest of MIRRORS) {
    if (existsSync(dest) && !existsSync(join(dest, MARKER))) {
      console.log(`sync-skills: ${dest} was not generated by this hook; leaving it alone.`)
      continue
    }
    rmSync(dest, { recursive: true, force: true })
    mkdirSync(dest, { recursive: true })
    writeFileSync(join(dest, MARKER), 'Generated from skills/ by .claude/hooks/sync-skills.mjs. Edit skills/ instead.\n')
    for (const { base, names } of groups) {
      for (const name of names) cpSync(join(base, name), join(dest, name), { recursive: true })
    }
  }
}

function describe(base, name) {
  const text = readFileSync(join(base, name, 'SKILL.md'), 'utf8')
  const match = text.match(/^description:\s*(.+)$/m)
  const first = (match?.[1] ?? '').split(/(?<=\.)\s/)[0]
  return first.length > 120 ? `${first.slice(0, 117)}...` : first
}

/** Vendored skills grouped by the upstream they came from, so the listing stays one line each. */
function vendorBySource(names) {
  const manifest = join(VENDOR, 'vendored.json')
  if (!existsSync(manifest)) return [['vendor', names]]
  const { skills = [] } = JSON.parse(readFileSync(manifest, 'utf8'))
  const owner = new Map(skills.map((s) => [s.name, s.source]))
  const groups = new Map()
  for (const name of names) {
    const key = owner.get(name) ?? 'unpinned'
    if (!groups.has(key)) groups.set(key, [])
    groups.get(key).push(name)
  }
  return [...groups]
}

try {
  const first = skillsIn(SOURCE).filter((n) => n !== 'vendor')
  const vendored = skillsIn(VENDOR).filter((n) => !first.includes(n))
  mirror([
    { base: VENDOR, names: vendored },
    { base: SOURCE, names: first }, // second, so a first-party skill wins a name collision
  ])
  const lines = [
    'Alcidion API. ASP.NET Core 9, two bounded contexts talking through events.',
    '',
    'Rules that are not negotiable (full set in .agents/AGENTS.md):',
    '  - Failing test first, named for the behaviour. Never weaken a test to get green.',
    '  - Invariants are enforced by the write (TryAddAsync / TryAddActiveAsync), never check-then-insert.',
    '  - Admissions may reference Alcidion.Patients.Contracts and nothing else from Patients.',
    '  - Expected failures are Result<T>; status codes are mapped only in ApiController.FromError.',
    '  - Time comes from IClock. Correlation ids come from the logging scope, not parameters.',
    '  - Middleware order in Program.cs is load-bearing; justify any new position.',
    '',
    `Project skills (${first.length}, source of truth in skills/):`,
    ...first.map((n) => `  - ${n}: ${describe(SOURCE, n)}`),
  ]
  if (vendored.length) {
    lines.push(
      '',
      `Vendored skills (${vendored.length}, pinned copies in skills/vendor/ - read them, never edit them):`,
      ...vendorBySource(vendored).map(([source, names]) => `  - ${source}: ${names.join(', ')}`),
    )
  }
  lines.push('', 'Verify with: dotnet test (39 tests, ~5s warm). The Stop hook runs it when .cs files changed.')
  console.log(lines.join('\n'))
} catch (err) {
  console.log(`sync-skills: skipped (${err.message})`)
}
